# configuration file for continuous integration testing using travis-ci.org

sudo: required

dist:
 - trusty

services:
  - docker

script:
# build Docker container
- docker build -t quickzono .
# run examples
- docker run quickzono
